export DISPLAY=

test: clean
	gbp buildpackage --git-builder="debuild -us -uc"
	lintian packages/*.deb --fail-on-warnings
	pbuilder-dist xenial build packages/*.dsc

sign: clean
	gbp buildpackage --git-builder="debuild -S"

clean:
	@git clean -f -X -d

.PHONY: test sign update clean

# vim: ts=2:sw=2:noet
