export DISPLAY=

test: clean
	gbp buildpackage --git-builder="debuild -us -uc"
	lintian packages/*.deb packages/*.dsc --fail-on-warnings
	pbuilder-dist `ls packages/*.dsc | perl -ne'/~([^~]+?)\d+\.dsc$$/ && print $$1'` build packages/*.dsc

sign: clean
	gbp buildpackage --git-builder="debuild -S"

clean:
	@git clean -f -X -d -q

.PHONY: test sign update clean

# vim: ts=2:sw=2:noet
